package se.ju.taun15a16.group5.mjilkmjecipes.backend.rest;

/**
 * Created by kevin on 20.11.2016.
 */

public enum RESTErrorCodes {
    USERNAME_MISSING,
    INVALID_USERNAME,
    DUPLICATE_USERNAME,
    PASSWORD_MISSING,
    PASSWORD_TOO_SHORT,
    PASSWORD_REQUIRES_NON_ALPHANUMERIC,
    PASSWORD_REQUIRES_DIGIT,
    PASSWORD_REQUIRES_LOWER,
    PASSWORD_REQUIRES_UPPER,
    TOKEN_MISING,
    TOKEN_INVALID,
    LONGITUDE_MISSING,
    LATITUDE_MISSING,
    RECIPE_ID_DOES_NOT_EXIST,
    INVALID_REQUREST,
    UNSUPPORTED_GRANT_TYPE,
    INVALID_CLIENT,
    NAME_MISSING,
    NAME_WRONG_LENGTH,
    DESCRIPTION_MISSING,
    DESCRIPTION_WRONG_LENGTH,
    DIRECTIONS_MISSING,
    DIRECTION_ORDER_MISSING,
    DIRECTION_DESCRIPTION_MISSING,
    DIRECTION_DESCRIPTION_WRONG_LENGTH,
    TEXT_MISSING,
    TEXT_WRONG_LENGTH,
    GRADE_MISSING,
    GRADE_WRONG_VALUE,
    COMMENTER_ID_MISSING,
    COMMENTER_ALREADY_COMMENT,
    TERM_MISSING,

}
